### PR TITLE
[utils] use keyword "override" for virtual methods

### PR DESCRIPTION
**Pull request by wgtdkp**

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Comment by bukepo** [comment]
where is the code coverage report?

**Comment by wgtdkp** [comment]
> where is the code coverage report?

Seems @simonlingoogle 's PR is trying to fix it: https://github.com/openthread/ot-br-posix/pull/654

**Review by Irving-cl — APPROVED** [review]
LGTM :+1:

**Review by jwhui — APPROVED** [review]

**Pull request merged**
