### PR TITLE
Hide AppendAutoAttachDisableArg when it is not used

### PR DESCRIPTION
**Pull request by yunanchangCorp**
That is, when __ANDROID__ is defined

### CODE REVIEW

**Comment by wgtdkp** [comment]
Curious, is this giving you build warnings?

**Review by wgtdkp — APPROVED** [review]

**Comment by yunanchangCorp** [comment]
yes, with some internal build I'm getting unused function
(not sure if it's ok to talk about the details here, you can ping me with chat if you want to discuss, ldap is yunanchang)

**Comment by yunanchangCorp** [comment]
force push to update the email, trying to get around the CLA problem

**Review by superwhd — APPROVED** [review]
LGTM 👍

**Review by bukepo — APPROVED** [review]

**Comment by wgtdkp** [comment]
@yunanchangCorp I am submitting https://github.com/openthread/ot-br-posix/pull/2333 to fix the issue you are facing with "non-standard" android platforms. PTAL

**Comment by yunanchangCorp** [comment]
@wgtdkp looks good (probably, only applied the latest change but not the one 4 days ago), though it will affect code so you can sync with Jason. I'll try again after the code is sync to internal repo.

**Comment by yunanchangCorp** [comment]
Closing this PR as #2333 is merged

**Pull request closed without merging**
