### PR TITLE
[mle] remove secure data request mode bit

### PR DESCRIPTION
**Pull request by jwhui**

### CODE REVIEW

**Review by librasungirl — APPROVED** [review]

**Review by gjc13 — APPROVED** [review]

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Comment by gjc13** [comment]
Shall we wait until https://github.com/openthread/openthread/pull/5560 is merged in openthread?

**Comment by jwhui** [comment]
> Shall we wait until [openthread/openthread#5560](https://github.com/openthread/openthread/pull/5560) is merged in openthread and update the submodule as well?
> 
> Otherwise the secure mode bit will be uninitialized.

We have a chicken-and-egg problem here since GitHub Actions in openthread/openthread requires specifying the openthread/ot-br-posix commit. At the same time, this repo specifies the openthread/openthread commit with submodule. Thoughts?

**Comment by gjc13** [comment]
> > Shall we wait until [openthread/openthread#5560](https://github.com/openthread/openthread/pull/5560) is merged in openthread and update the submodule as well?
> > Otherwise the secure mode bit will be uninitialized.
> 
> We have a chicken-and-egg problem here since GitHub Actions in openthread/openthread requires specifying the openthread/ot-br-posix [commit](https://github.com/openthread/openthread/blob/6c6d5f617991d543b9332432866504e8e21c28f4/.github/workflows/simulation-1.2.yml#L230). At the same time, this repo specifies the openthread/openthread commit with submodule. Thoughts?

Then we can merge this one first since the all the checks are fine here.

**Pull request merged**
