### PR TITLE
[rest] support deleting the dataset

### PR DESCRIPTION
**Pull request by agners**
Add REST API to support deleting the active or pending operational dataset. Deleting the active operational dataset requires the Thread network to be disabled (just like modifying the active operational dataset). Subsequent use of the PUT method allows to build entirly new datasets with values generated by the stack (through otDatasetCreateNewNetwork).

### CODE REVIEW

**Comment by agners** [comment]
The macOS issue is kinda weird, I rebased  on an earlier commit which built fine according to the main branch. It seems some external resource changed which broke the `macOS / build-check` here?

**Comment by agners** [comment]
> There are also other persistent data that you probably want to remove as well when joining a new network. OpenThread provides `otInstanceErasePersistentInfo()` to erase all those data. What about we provide an equivalent REST API?

Hm, `otInstanceErasePersistentInfo()` probably would need another REST resource path. Maybe a `DELETE` on `/node`?

What type of data is that erasing beside the dataset? I was assuming that all network related data is being reset by clearing the dataset.

**Comment by jwhui** [comment]
> What type of data is that erasing beside the dataset? I was assuming that all network related data is being reset by clearing the dataset.

All of the non-volatile settings are defined here: https://github.com/openthread/openthread/blob/main/src/core/common/settings.hpp

Thread Specification requires certain identifying information to be reset on a factory reset.

If we are truly want to factory reset the Thread configuration, then we should erase all non-volatile settings.

I wonder if we should provide a way to delete all non-volatile settings rather than just the Operational Dataset itself.

**Comment by agners** [comment]
Replaced by #1908.

**Pull request closed without merging**
