### PR TITLE
[openwrt] fix startup script no effect

### PR DESCRIPTION
**Pull request by IHIDCHAOS**
The statement script needs to be on the first line, otherwise executing "/etc/init.d/otbr-agent start" has no effect.

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Comment by IHIDCHAOS** [comment]
the "Build / rest-check (rest-off) (pull_request)"check failed. 
it shows **RadioNoResponse**, and i dont know if its because of the "ttyUSB0" and "ttyACM0".

**Comment by bukepo** [comment]
> the "Build / rest-check (rest-off) (pull_request)"check failed.
> it shows **RadioNoResponse**, and i dont know if its because of the "ttyUSB0" and "ttyACM0".

You may try reverting that change.

**Comment by IHIDCHAOS** [comment]
> > the "Build / rest-check (rest-off) (pull_request)"check failed.
> > it shows **RadioNoResponse**, and i dont know if its because of the "ttyUSB0" and "ttyACM0".
> 
> You may try reverting that change.

reverted

**Review by jwhui — APPROVED** [review]
Thanks! 👍

**Pull request merged**
