### PR TITLE
[test] verify if LGTM.com works

### PR DESCRIPTION
**Pull request by simonlingoogle**

### CODE REVIEW

**Comment by Irving-cl** [comment]
It looks that many projects are experiencing this problem: https://github.community/t/lgtm-cannot-spot-issue-in-checkout/148935

**Comment by jwhui** [comment]
> It looks that many projects are experiencing this problem: https://github.community/t/lgtm-cannot-spot-issue-in-checkout/148935

Here too: https://github.com/github/codeql/issues/4809#issuecomment-742988034

**Comment by Irving-cl** [comment]
We can skip the analysis until it's fixed: https://lgtm.com/help/lgtm/using-automated-code-review#skipping-pr-analysis

We have to login first on lgtm.com

**Comment by jwhui** [comment]
A fix has been submitted for LGTM.com https://github.com/github/codeql/issues/4809#issuecomment-743142125

**Pull request closed without merging**
