### PR TITLE
[web] bump to latest Simple-Web-Server version

### PR DESCRIPTION
**Pull request by agners**
Bump Simple-Web-Server to the latest git commit. This also fixes a compile issue seen with GCC 12.2.0:

```
In file included from /home/sag/projects/openthread/ot-br-posix/src/web/web-service/web_server.cpp:42: /home/sag/projects/openthread/ot-br-posix/third_party/Simple-web-server/repo/server_http.hpp: In instantiation of ‘SimpleWeb::ServerBase<socket_type>::Request::Request(const socket_type&) [with socket_type = boost::asio::basic_stream_socket<boost::asio::ip::tcp>]’:
/home/sag/projects/openthread/ot-br-posix/third_party/Simple-web-server/repo/server_http.hpp:460:74:   required from here
/home/sag/projects/openthread/ot-br-posix/third_party/Simple-web-server/repo/server_http.hpp:119:57: error: member ‘SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request::streambuf’ is used uninitialized [-Werror=uninitialized]
  119 |             Request(const socket_type &socket): content(streambuf) {
      |                                                         ^~~~~~~~~
```

### CODE REVIEW

**Comment by wgtdkp** [comment]
@agners Just FYI, in case you want a production-class web server, https://github.com/openthread/ot-br-posix/pull/537 is a PR which replaces the Simple-Web-Server with Nginx and provides complete RESTful API set which is comparable with d-bus.

**Comment by agners** [comment]
@wgtdkp hm, interesting PR, wasn't aware of that effort thanks for linking. I am not particularly interested in the web interface, I use it more as a development/debugging tool right now. In the end we will disable it most likely. However, the changes to the REST seems to be interesting. The PR seems to do quite a bit for a single PR, maybe splitting out the REST changes would be a first step?

**Comment by wgtdkp** [comment]
>  The PR seems to do quite a bit for a single PR, maybe splitting out the REST changes would be a first step?

@agners Agree, it sounds to be reasonable and easier to forward!

**Comment by jwhui** [comment]
@agners @wgtdkp , I'm supportive of pulling forward (portions of) #537. In the meantime, would it make sense to merge this PR first?

**Comment by agners** [comment]
@jwhui yes I think merging this still make sense. It fixes the build problem for the time being.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
