### PR TITLE
[platform] verify Network Manager with BeagleBone

### PR DESCRIPTION
**Pull request by srickardti**
This allows building for BeagleBone in the same fashion as RasPi.

BeagleBone uses connaman by default for network management. The [BeagleBone Black build guide](https://openthread.io/guides/border-router/beaglebone-black) should be updated to explain how to replace connman with Network Manager.

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Review by jwhui — APPROVED** [review]

**Comment by jwhui** [comment]
> BeagleBone uses connaman by default for network management. The [BeagleBone Black build guide](https://openthread.io/guides/border-router/beaglebone-black) should be updated to explain how to replace connman with Network Manager.

@srickardti , will you provide updates for the BeagleBone Black build guide?

**Comment by srickardti** [comment]
> @srickardti , will you provide updates for the BeagleBone Black build guide?

@jwhui absolutely, just let me know where and in what format to provide those updates.

**Comment by Vyrastas** [comment]
Hey @srickardti Actually just today I've been implementing a new process where documentation is sourced on GitHub and mirrored to openthread.io, to better enable outside contributions... if you can wait a day or two I'll add the source Markdown for https://openthread.io/guides/border-router/beaglebone-black here on GitHub, and you can just edit it directly.  Then I'll import your updated version into openthread.io.  Sound good?

**Comment by srickardti** [comment]
@Vyrastas sounds good to me

**Comment by srickardti** [comment]
Updates to the documentation have been pushed and offered on this PR https://github.com/openthread/openthread/pull/5606.

@Vyrastas , @jwhui , let me know if there is too much or too little.

**Pull request merged**
