### PR TITLE
[trel] enable TREL by default

### PR DESCRIPTION
**Pull request by simonlingoogle**
This commit enables TREL by default.

**TREL is enabled by default using the Backbone interface**

- [x] Make sure OTBR setup works with TREL enabled

### CODE REVIEW

**Review by bukepo — APPROVED** [review]
I prefer a more extensible syntax:

```bash
ot-cli trel://eth0
```

**Comment by simonlingoogle** [comment]
> I prefer a more extensible syntax:
> 
> ```shell
> ot-cli trel://eth0
> ```

URL is more flexible if we have arguments for TREL. 
But there isn't any for now. 

**I'd prefer to add features only when they are useful.**

**Review by abtink — APPROVED** [review]
LGTM. Thanks. 👍

**Comment by simonlingoogle** [comment]
As suggested by @wgtdkp , I removed `-T <trel-ifname>` and use existing argument `-B <backbone-ifname>` for TREL interface because we don't have a use case to use different infrastructure links for `Border/Backbone Router` and `TREL`.

Thoughts?

**Review by wgtdkp — APPROVED** [review]
LGTM :+1:

**Comment by abtink** [comment]
> As suggested by @wgtdkp , I removed -T <trel-ifname> and use existing argument -B <backbone-ifname> for TREL interface because we don't have a use case to use different infrastructure links for Border/Backbone Router and TREL.
> 
> Thoughts?

Thanks @simonlingoogle, I feel keeping the two (backbone and trel) separate as you have originally in this PR may be a good idea.

- While I agree we may not use them together, fundamentally (from what each of these do) they are two unrelated functionality/features in OT and Thread and can potentially be used together.
- Also having different argument names makes the intention of what is being used more explicit and clear (e.g., `-T <trel-ifname>` makes it clear it is setting trel ifname).
- The one advantage I see with combining the args is to reuse code but not sure if code size is a big factor for `ot-br-posix`.

**Comment by simonlingoogle** [comment]
> * While I agree we may not use them together, fundamentally (from what each of these do) they are two unrelated functionality/features in OT and Thread and can potentially be used together.
> * Also having different argument names makes the intention of what is being used more explicit and clear (e.g., `-T <trel-ifname>` makes it clear it is setting trel ifname).
> * The one advantage I see with combining the args is to reuse code but not sure if code size is a big factor for `ot-br-posix`.

Agree with you on the benefits. And code size is not an issue for `otbr`. 

Will restore it back to use `-T <trel-ifname>`. Thanks.

**Comment by gabekassel** [comment]
Is this case sensitive? Should this be `-t` to match [Openthread](https://github.com/openthread/openthread/pull/4440/files#diff-0e68f9e173660fad0412aa18c799123ae39a8b618bae1a05ec54315912f6d3a8R145)?

**Comment by simonlingoogle** [comment]
> Is this case sensitive? Should this be `-t` to match [Openthread](https://github.com/openthread/openthread/pull/4440/files#diff-0e68f9e173660fad0412aa18c799123ae39a8b618bae1a05ec54315912f6d3a8R145)? 

Good question. Actually we are going to change to use url like trek://eth0. Neither -t nor -T will be used.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
