### PR TITLE
[docker] log output of wpantund to a file

### PR DESCRIPTION
**Pull request by KaSroka**

### CODE REVIEW

**Comment by jwhui** [comment]
@KaSroka, thanks for looking into this!

What about leveraging syslog? You can find an example here:
- https://github.com/openthread/openthread/blob/master/etc/docker/environment/

**Comment by KaSroka** [comment]
@jwhui I'll take a look into this - I wanted to use syslog but it failed. I'll check if the solution from this example helps.

**Comment by shalak** [comment]
@KaSroka What's the status of this? We could really benefit from this feature.

**Comment by KaSroka** [comment]
I haven't tried the syslog approach due to lack of time.

Pobierz aplikacje Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by jwhui** [comment]
@shalak, I submitted #266 to enable syslog in docker image. Please review.

**Comment by jwhui** [comment]
Superseded by #266.

**Pull request closed without merging**
