### PR TITLE
[openwrt] enable `OTBR_NAT64` and `INFRA_IF` by default and add UCI config

### PR DESCRIPTION
**Pull request by ihidchaos**
This commit enables OTBR_NAT64 and INFRA_IF by default, making NAT64 functionality available out-of-the-box on the OpenWrt platform.

At the same time, the RCP serial port configuration is added to the UCI configuration file to make the runtime modifications clearer and to avoid the errors that are easily caused by directly modifying the init.d configuration.

### CODE REVIEW

**Comment by ihidchaos** [comment]
image

The CI/CD passed automatically again without making changes. I guess we need to improve the number of concurrencies in CI/CI to make it a single step test?

In any case, can someone merge it in? @bukepo @xuyirio thanks.

**Review by xuyirio — APPROVED** [review]
LGTM. 

One thing to note: querying an AIL NAT64 prefix is currently disabled for OpenWRT ([PR](https://github.com/openthread/openthread/pull/8065)).

**Comment by ihidchaos** [comment]
> LGTM.
> 
> One thing to note: querying an AIL NAT64 prefix is currently disabled for OpenWRT ([PR](https://github.com/openthread/openthread/pull/8065)).

According to the description of [openwrt/pull/11559](https://github.com/openwrt/openwrt/pull/11559), libanl is already included in the musl c library, so we can turn this option on.

Do I need to also submit a modification to [CMakeLists.txt#L153](https://github.com/openthread/openthread/blob/07c56c28e03c298032e446befab0819d5b4121b5/src/posix/platform/CMakeLists.txt#L153) PR?

**Comment by xuyirio** [comment]
> > LGTM.
> > One thing to note: querying an AIL NAT64 prefix is currently disabled for OpenWRT ([PR](https://github.com/openthread/openthread/pull/8065)).
> 
> According to the description of [openwrt/pull/11559](https://github.com/openwrt/openwrt/pull/11559), libanl is already included in the musl c library, so we can turn this option on.
> 
> Do I need to also submit a modification to [CMakeLists.txt#L153](https://github.com/openthread/openthread/blob/07c56c28e03c298032e446befab0819d5b4121b5/src/posix/platform/CMakeLists.txt#L153) PR?

Good to know! Yes, please remove the `NOT OT_TARGET_OPENWRT` condition and verify the tests are passing.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
