### PR TITLE
[mac-filter] change whitelist/blacklist to allowlist/denylist

### PR DESCRIPTION
**Pull request by jwhui**
To promote inclusivity and eliminate any unintentional bias.

### CODE REVIEW

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Review by bukepo — COMMENTED** [review]
Should this PR update submodule of OpenThread ?

**Comment by bukepo** [comment]
Can we merge this PR or merge https://github.com/openthread/ot-br-posix/pull/557 into this PR?

**Comment by jwhui** [comment]
> Can we merge this PR or merge #557 into this PR?

I just cherry-picked 19e32d148ef478e3b335964764240d3621e7c3b3 into this PR.

**Comment by simonlingoogle** [comment]
Labeled as P2 since many other PRs are depending on this PR. @jwhui @bukepo

**Pull request merged**
