### PR TITLE
[build] add package otbr onto OpenWRT files.

### PR DESCRIPTION
**Pull request by huamenggg**
This commit adds three files for packaging otbr onto OpenWRT.
README.md is the instruction of operations.
feeds.conf is feed file for OpenWRT.
Makefile is to package the otbr project.

### CODE REVIEW

**Comment by bukepo** [comment]
I tend to create a orphan branch for this, @jwhui Thoughts?

**Comment by jwhui** [comment]
I think an orphan branch makes sense in this case.

**Comment by bukepo** [comment]
@jwhui Just created the orphan branch. https://github.com/openthread/ot-br-posix/tree/openwrt/openthread

**Comment by bukepo** [comment]
@jwhui any comments?

**Comment by jwhui** [comment]
@bukepo, I reviewed this PR and it looks fine. However, it currently targets master branch rather than openwrt branch. Is that intentional?

**Comment by huamenggg** [comment]
Wrong to push to master branch.

**Pull request closed without merging**
