### PR TITLE
[utils] add `OTBR_DISALLOW_COPY_AND_ASSIGN`

### PR DESCRIPTION
**Pull request by simonlingoogle**
This commit uses `OTBR_DISALLOW_COPY_AND_ASSIGN` to make sure certain objects are never copied.

Should choose the preferred one of https://github.com/openthread/ot-br-posix/pull/1177 and this PR.

### CODE REVIEW

**Review by superwhd — APPROVED** [review]
LGTM overall with a question: Why not follow the pattern in [`third_party/openthread/repo/src/core/common/non_copyable.hpp`?](https://github.com/openthread/openthread/blob/main/src/core/common/non_copyable.hpp)?

**Review by zhanglongxia — APPROVED** [review]
LGTM

**Comment by simonlingoogle** [comment]
> LGTM overall with a question: Why not follow the pattern in [`third_party/openthread/repo/src/core/common/non_copyable.hpp`?](https://github.com/openthread/openthread/blob/main/src/core/common/non_copyable.hpp)?

Tried that way, but didn't work out well.

**Comment by simonlingoogle** [comment]
close in favor of https://github.com/openthread/ot-br-posix/pull/1177

**Pull request closed without merging**
