### PR TITLE
[mdns] silence unused parameter warning when compiling without assert

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**

### CODE REVIEW

**Review by wgtdkp — APPROVED** [review]
Thanks! LGTM 👍

**Comment by markus-becker-tridonic-com** [comment]
@wgtdkp please also take a look at https://github.com/openthread/openthread/pull/6410 (was discovered on the same toolchain).

**Comment by markus-becker-tridonic-com** [comment]
@wgtdkp any other approval required for this PR to be merged?

**Comment by wgtdkp** [comment]
> @wgtdkp any other approval required for this PR to be merged?

I requested @jwhui to merge this PR. Thanks for your contribution! @markus-becker-tridonic-com

**Review by jwhui — APPROVED** [review]

**Pull request merged**
