### PR TITLE
[setup] fix libjsoncpp1 not found on Ubuntu 21.04

### PR DESCRIPTION
**Pull request by simonlingoogle**
Fixes https://github.com/project-chip/connectedhomeip/issues/8235

Installing `libjsoncpp-dev` on Ubuntu since it will automatically install the correct `libjsoncpp<Version>` package.

**Ubuntu 21.04:**
```
# apt install libjsoncpp-dev
The following NEW packages will be installed:
  libjsoncpp-dev libjsoncpp24
```

**Ubuntu 18.04:**
```
# apt install libjsoncpp-dev
The following NEW packages will be installed:
  libjsoncpp-dev libjsoncpp1
```

### CODE REVIEW

**Review by librasungirl — APPROVED** [review]

**Review by wgtdkp — APPROVED** [review]
Add ubuntu:21.04 CI tests?

**Review by LuDuda — APPROVED** [review]

**Comment by jwhui** [comment]
@simonlingoogle , some GitHub Actions checks are failing. Can you help take a look?

**Comment by simonlingoogle** [comment]
> Add ubuntu:21.04 CI tests?

Added docker build for ubuntu 21.04

**Comment by simonlingoogle** [comment]
> @simonlingoogle , some GitHub Actions checks are failing. Can you help take a look?

Seems it's constantly failing. Didn't expect that. Will take a look.

**Comment by simonlingoogle** [comment]
> @simonlingoogle , some GitHub Actions checks are failing. Can you help take a look?

The checks failed because we removed libjsoncpp-dev in Dockerfile for cleanup, which will in turn remove libjsoncpp1 or libjsoncpp24. We didn't have this problem because libjsoncpp1 was explicitly installed using apt-get so it won't be automatically removed. 

I think we can keep `libjsoncpp-dev` installed to address this issue, which I pushed. 
@jwhui

**Review by jwhui — APPROVED** [review]

**Pull request merged**
