### PR TITLE
[certification] return ipv6 in testharness-discovery script

### PR DESCRIPTION
**Pull request by tomaszkob89**
Current implementation returns on Windows platforms by default IPv4 address and with this PR we will start to return IPv6 link local.

### CODE REVIEW

**Comment by simonlingoogle** [comment]
Why use IPv6 address instead?

**Comment by tomaszkob89** [comment]
> 

It is less error-prone based on our experience. We have observed issues introduced by the use of IPv4 in the tests. Besides that e.g. Kirale BR utilizes IPv6 from the beginning and we would like to comply. 

@edmont could you add something?

**Comment by edmont** [comment]
Basically the IPv6 link local address remains constant across reboots but the IPv4 address might change depending on the availability of a DHCP server. We have observed cases in which the BR reports some address in the discovery mechanism to which it doesn't respond by the time the harness tries to send some commands.

**Review by edmont — APPROVED** [review]

**Comment by simonlingoogle** [comment]
> Basically the IPv6 link local address remains constant across reboots but the IPv4 address might change depending on the availability of a DHCP server. We have observed cases in which the BR reports some address in the discovery mechanism to which it doesn't respond by the time the harness tries to send some commands.

Thanks for clarification. Advertising IPv6 address should be fine as long as Harness supports it.

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
