### PR TITLE
[logging] allow syslog facility to be defined

### PR DESCRIPTION
**Pull request by gabekassel**
It's useful to change the syslog facility to send OTBR logs elsewhere. This creates a new define, defaults it to `LOG_USER`, and allows it to be passed as a cmake flag. 

**Testing**
Built into our larger system with flag set to `-DOTBR_SYSLOG_FACILITY_ID="LOG_LOCAL5" ` and syslog configured to send `local5` to `/var/log/openthread` -- resulted in logs correctly going to that path.

### CODE REVIEW

**Comment by gabekassel** [comment]
i signed it

**Comment by gabekassel** [comment]
@jwhui looks like different tests are failing each run. i've seen backbone router, trel, and another mdns test all fail. any suggestions?

**Comment by gabekassel** [comment]
@jwhui @simonlingoogle who should/can review this? Thanks!

**Comment by jwhui** [comment]
> @jwhui @simonlingoogle who should/can review this? Thanks!

I've tagged @bukepo

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Comment by gabekassel** [comment]
@jwhui can this merge today?

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
